/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.factory;

import java.sql.Connection;
import edu.co.sena.dao.*;
import edu.co.sena.jdbc.*;

public class CarritoComprasDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return CarritoComprasDao
	 */
	public static CarritoComprasDao create()
	{
		return new CarritoComprasDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return CarritoComprasDao
	 */
	public static CarritoComprasDao create(Connection conn)
	{
		return new CarritoComprasDaoImpl( conn );
	}

}
