/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.dto;

import edu.co.sena.dao.*;
import edu.co.sena.factory.*;
import edu.co.sena.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class CarritoCompras implements Serializable
{
	/** 
	 * This attribute maps to the column idCARRITO in the carrito_compras table.
	 */
	protected String idCARRITO;

	/** 
	 * This attribute represents whether the attribute idCARRITO has been modified since being read from the database.
	 */
	protected boolean idCARRITOModified = false;

	/** 
	 * This attribute maps to the column TOTAL in the carrito_compras table.
	 */
	protected double total;

	/** 
	 * This attribute represents whether the attribute total has been modified since being read from the database.
	 */
	protected boolean totalModified = false;

	/** 
	 * This attribute maps to the column SUBTOTAL in the carrito_compras table.
	 */
	protected double subtotal;

	/** 
	 * This attribute represents whether the attribute subtotal has been modified since being read from the database.
	 */
	protected boolean subtotalModified = false;

	/** 
	 * This attribute maps to the column IMPUESTOS in the carrito_compras table.
	 */
	protected double impuestos;

	/** 
	 * This attribute represents whether the attribute impuestos has been modified since being read from the database.
	 */
	protected boolean impuestosModified = false;

	/**
	 * Method 'CarritoCompras'
	 * 
	 */
	public CarritoCompras()
	{
	}

	/**
	 * Method 'getIdCARRITO'
	 * 
	 * @return String
	 */
	public String getIdCARRITO()
	{
		return idCARRITO;
	}

	/**
	 * Method 'setIdCARRITO'
	 * 
	 * @param idCARRITO
	 */
	public void setIdCARRITO(String idCARRITO)
	{
		this.idCARRITO = idCARRITO;
		this.idCARRITOModified = true;
	}

	/** 
	 * Sets the value of idCARRITOModified
	 */
	public void setIdCARRITOModified(boolean idCARRITOModified)
	{
		this.idCARRITOModified = idCARRITOModified;
	}

	/** 
	 * Gets the value of idCARRITOModified
	 */
	public boolean isIdCARRITOModified()
	{
		return idCARRITOModified;
	}

	/**
	 * Method 'getTotal'
	 * 
	 * @return double
	 */
	public double getTotal()
	{
		return total;
	}

	/**
	 * Method 'setTotal'
	 * 
	 * @param total
	 */
	public void setTotal(double total)
	{
		this.total = total;
		this.totalModified = true;
	}

	/** 
	 * Sets the value of totalModified
	 */
	public void setTotalModified(boolean totalModified)
	{
		this.totalModified = totalModified;
	}

	/** 
	 * Gets the value of totalModified
	 */
	public boolean isTotalModified()
	{
		return totalModified;
	}

	/**
	 * Method 'getSubtotal'
	 * 
	 * @return double
	 */
	public double getSubtotal()
	{
		return subtotal;
	}

	/**
	 * Method 'setSubtotal'
	 * 
	 * @param subtotal
	 */
	public void setSubtotal(double subtotal)
	{
		this.subtotal = subtotal;
		this.subtotalModified = true;
	}

	/** 
	 * Sets the value of subtotalModified
	 */
	public void setSubtotalModified(boolean subtotalModified)
	{
		this.subtotalModified = subtotalModified;
	}

	/** 
	 * Gets the value of subtotalModified
	 */
	public boolean isSubtotalModified()
	{
		return subtotalModified;
	}

	/**
	 * Method 'getImpuestos'
	 * 
	 * @return double
	 */
	public double getImpuestos()
	{
		return impuestos;
	}

	/**
	 * Method 'setImpuestos'
	 * 
	 * @param impuestos
	 */
	public void setImpuestos(double impuestos)
	{
		this.impuestos = impuestos;
		this.impuestosModified = true;
	}

	/** 
	 * Sets the value of impuestosModified
	 */
	public void setImpuestosModified(boolean impuestosModified)
	{
		this.impuestosModified = impuestosModified;
	}

	/** 
	 * Gets the value of impuestosModified
	 */
	public boolean isImpuestosModified()
	{
		return impuestosModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CarritoCompras)) {
			return false;
		}
		
		final CarritoCompras _cast = (CarritoCompras) _other;
		if (idCARRITO == null ? _cast.idCARRITO != idCARRITO : !idCARRITO.equals( _cast.idCARRITO )) {
			return false;
		}
		
		if (idCARRITOModified != _cast.idCARRITOModified) {
			return false;
		}
		
		if (total != _cast.total) {
			return false;
		}
		
		if (totalModified != _cast.totalModified) {
			return false;
		}
		
		if (subtotal != _cast.subtotal) {
			return false;
		}
		
		if (subtotalModified != _cast.subtotalModified) {
			return false;
		}
		
		if (impuestos != _cast.impuestos) {
			return false;
		}
		
		if (impuestosModified != _cast.impuestosModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idCARRITO != null) {
			_hashCode = 29 * _hashCode + idCARRITO.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idCARRITOModified ? 1 : 0);
		long temp_total = Double.doubleToLongBits(total);
		_hashCode = 29 * _hashCode + (int) (temp_total ^ (temp_total >>> 32));
		_hashCode = 29 * _hashCode + (totalModified ? 1 : 0);
		long temp_subtotal = Double.doubleToLongBits(subtotal);
		_hashCode = 29 * _hashCode + (int) (temp_subtotal ^ (temp_subtotal >>> 32));
		_hashCode = 29 * _hashCode + (subtotalModified ? 1 : 0);
		long temp_impuestos = Double.doubleToLongBits(impuestos);
		_hashCode = 29 * _hashCode + (int) (temp_impuestos ^ (temp_impuestos >>> 32));
		_hashCode = 29 * _hashCode + (impuestosModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CarritoComprasPk
	 */
	public CarritoComprasPk createPk()
	{
		return new CarritoComprasPk(idCARRITO);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.dto.CarritoCompras: " );
		ret.append( "idCARRITO=" + idCARRITO );
		ret.append( ", total=" + total );
		ret.append( ", subtotal=" + subtotal );
		ret.append( ", impuestos=" + impuestos );
		return ret.toString();
	}

}
