/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the catalogo table.
 */
public class CatalogoPk implements Serializable
{
	protected int idCatologo;

	/** 
	 * This attribute represents whether the primitive attribute idCatologo is null.
	 */
	protected boolean idCatologoNull;

	/** 
	 * Sets the value of idCatologo
	 */
	public void setIdCatologo(int idCatologo)
	{
		this.idCatologo = idCatologo;
	}

	/** 
	 * Gets the value of idCatologo
	 */
	public int getIdCatologo()
	{
		return idCatologo;
	}

	/**
	 * Method 'CatalogoPk'
	 * 
	 */
	public CatalogoPk()
	{
	}

	/**
	 * Method 'CatalogoPk'
	 * 
	 * @param idCatologo
	 */
	public CatalogoPk(final int idCatologo)
	{
		this.idCatologo = idCatologo;
	}

	/** 
	 * Sets the value of idCatologoNull
	 */
	public void setIdCatologoNull(boolean idCatologoNull)
	{
		this.idCatologoNull = idCatologoNull;
	}

	/** 
	 * Gets the value of idCatologoNull
	 */
	public boolean isIdCatologoNull()
	{
		return idCatologoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CatalogoPk)) {
			return false;
		}
		
		final CatalogoPk _cast = (CatalogoPk) _other;
		if (idCatologo != _cast.idCatologo) {
			return false;
		}
		
		if (idCatologoNull != _cast.idCatologoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idCatologo;
		_hashCode = 29 * _hashCode + (idCatologoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.dto.CatalogoPk: " );
		ret.append( "idCatologo=" + idCatologo );
		return ret.toString();
	}

}
