/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.dto;

import edu.co.sena.dao.*;
import edu.co.sena.factory.*;
import edu.co.sena.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Departamento implements Serializable
{
	/** 
	 * This attribute maps to the column idDEPARTAMENTO in the departamento table.
	 */
	protected int idDEPARTAMENTO;

	/** 
	 * This attribute represents whether the attribute idDEPARTAMENTO has been modified since being read from the database.
	 */
	protected boolean idDEPARTAMENTOModified = false;

	/** 
	 * This attribute maps to the column NOMBRE_DEPARAMENTO in the departamento table.
	 */
	protected String nombreDeparamento;

	/** 
	 * This attribute represents whether the attribute nombreDeparamento has been modified since being read from the database.
	 */
	protected boolean nombreDeparamentoModified = false;

	/**
	 * Method 'Departamento'
	 * 
	 */
	public Departamento()
	{
	}

	/**
	 * Method 'getIdDEPARTAMENTO'
	 * 
	 * @return int
	 */
	public int getIdDEPARTAMENTO()
	{
		return idDEPARTAMENTO;
	}

	/**
	 * Method 'setIdDEPARTAMENTO'
	 * 
	 * @param idDEPARTAMENTO
	 */
	public void setIdDEPARTAMENTO(int idDEPARTAMENTO)
	{
		this.idDEPARTAMENTO = idDEPARTAMENTO;
		this.idDEPARTAMENTOModified = true;
	}

	/** 
	 * Sets the value of idDEPARTAMENTOModified
	 */
	public void setIdDEPARTAMENTOModified(boolean idDEPARTAMENTOModified)
	{
		this.idDEPARTAMENTOModified = idDEPARTAMENTOModified;
	}

	/** 
	 * Gets the value of idDEPARTAMENTOModified
	 */
	public boolean isIdDEPARTAMENTOModified()
	{
		return idDEPARTAMENTOModified;
	}

	/**
	 * Method 'getNombreDeparamento'
	 * 
	 * @return String
	 */
	public String getNombreDeparamento()
	{
		return nombreDeparamento;
	}

	/**
	 * Method 'setNombreDeparamento'
	 * 
	 * @param nombreDeparamento
	 */
	public void setNombreDeparamento(String nombreDeparamento)
	{
		this.nombreDeparamento = nombreDeparamento;
		this.nombreDeparamentoModified = true;
	}

	/** 
	 * Sets the value of nombreDeparamentoModified
	 */
	public void setNombreDeparamentoModified(boolean nombreDeparamentoModified)
	{
		this.nombreDeparamentoModified = nombreDeparamentoModified;
	}

	/** 
	 * Gets the value of nombreDeparamentoModified
	 */
	public boolean isNombreDeparamentoModified()
	{
		return nombreDeparamentoModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Departamento)) {
			return false;
		}
		
		final Departamento _cast = (Departamento) _other;
		if (idDEPARTAMENTO != _cast.idDEPARTAMENTO) {
			return false;
		}
		
		if (idDEPARTAMENTOModified != _cast.idDEPARTAMENTOModified) {
			return false;
		}
		
		if (nombreDeparamento == null ? _cast.nombreDeparamento != nombreDeparamento : !nombreDeparamento.equals( _cast.nombreDeparamento )) {
			return false;
		}
		
		if (nombreDeparamentoModified != _cast.nombreDeparamentoModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDEPARTAMENTO;
		_hashCode = 29 * _hashCode + (idDEPARTAMENTOModified ? 1 : 0);
		if (nombreDeparamento != null) {
			_hashCode = 29 * _hashCode + nombreDeparamento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreDeparamentoModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DepartamentoPk
	 */
	public DepartamentoPk createPk()
	{
		return new DepartamentoPk(idDEPARTAMENTO);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.dto.Departamento: " );
		ret.append( "idDEPARTAMENTO=" + idDEPARTAMENTO );
		ret.append( ", nombreDeparamento=" + nombreDeparamento );
		return ret.toString();
	}

}
