/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.dto;

import edu.co.sena.dao.*;
import edu.co.sena.factory.*;
import edu.co.sena.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Domicilio implements Serializable
{
	/** 
	 * This attribute maps to the column idDOMICILIO in the domicilio table.
	 */
	protected int idDOMICILIO;

	/** 
	 * This attribute represents whether the attribute idDOMICILIO has been modified since being read from the database.
	 */
	protected boolean idDOMICILIOModified = false;

	/** 
	 * This attribute maps to the column DIRRECION in the domicilio table.
	 */
	protected String dirrecion;

	/** 
	 * This attribute represents whether the attribute dirrecion has been modified since being read from the database.
	 */
	protected boolean dirrecionModified = false;

	/** 
	 * This attribute maps to the column TELEFONO in the domicilio table.
	 */
	protected String telefono;

	/** 
	 * This attribute represents whether the attribute telefono has been modified since being read from the database.
	 */
	protected boolean telefonoModified = false;

	/** 
	 * This attribute maps to the column LOCALIDAD in the domicilio table.
	 */
	protected String localidad;

	/** 
	 * This attribute represents whether the attribute localidad has been modified since being read from the database.
	 */
	protected boolean localidadModified = false;

	/** 
	 * This attribute maps to the column BARRIO in the domicilio table.
	 */
	protected String barrio;

	/** 
	 * This attribute represents whether the attribute barrio has been modified since being read from the database.
	 */
	protected boolean barrioModified = false;

	/** 
	 * This attribute maps to the column CUENTA_TIPO_DOCUMENTO in the domicilio table.
	 */
	protected String cuentaTipoDocumento;

	/** 
	 * This attribute represents whether the attribute cuentaTipoDocumento has been modified since being read from the database.
	 */
	protected boolean cuentaTipoDocumentoModified = false;

	/** 
	 * This attribute maps to the column CUENTA_NUMERO_DOCUMENTO in the domicilio table.
	 */
	protected String cuentaNumeroDocumento;

	/** 
	 * This attribute represents whether the attribute cuentaNumeroDocumento has been modified since being read from the database.
	 */
	protected boolean cuentaNumeroDocumentoModified = false;

	/** 
	 * This attribute maps to the column MUNICIPIO_idMUNICIPIO in the domicilio table.
	 */
	protected int municipioIdmunicipio;

	/** 
	 * This attribute represents whether the attribute municipioIdmunicipio has been modified since being read from the database.
	 */
	protected boolean municipioIdmunicipioModified = false;

	/**
	 * Method 'Domicilio'
	 * 
	 */
	public Domicilio()
	{
	}

	/**
	 * Method 'getIdDOMICILIO'
	 * 
	 * @return int
	 */
	public int getIdDOMICILIO()
	{
		return idDOMICILIO;
	}

	/**
	 * Method 'setIdDOMICILIO'
	 * 
	 * @param idDOMICILIO
	 */
	public void setIdDOMICILIO(int idDOMICILIO)
	{
		this.idDOMICILIO = idDOMICILIO;
		this.idDOMICILIOModified = true;
	}

	/** 
	 * Sets the value of idDOMICILIOModified
	 */
	public void setIdDOMICILIOModified(boolean idDOMICILIOModified)
	{
		this.idDOMICILIOModified = idDOMICILIOModified;
	}

	/** 
	 * Gets the value of idDOMICILIOModified
	 */
	public boolean isIdDOMICILIOModified()
	{
		return idDOMICILIOModified;
	}

	/**
	 * Method 'getDirrecion'
	 * 
	 * @return String
	 */
	public String getDirrecion()
	{
		return dirrecion;
	}

	/**
	 * Method 'setDirrecion'
	 * 
	 * @param dirrecion
	 */
	public void setDirrecion(String dirrecion)
	{
		this.dirrecion = dirrecion;
		this.dirrecionModified = true;
	}

	/** 
	 * Sets the value of dirrecionModified
	 */
	public void setDirrecionModified(boolean dirrecionModified)
	{
		this.dirrecionModified = dirrecionModified;
	}

	/** 
	 * Gets the value of dirrecionModified
	 */
	public boolean isDirrecionModified()
	{
		return dirrecionModified;
	}

	/**
	 * Method 'getTelefono'
	 * 
	 * @return String
	 */
	public String getTelefono()
	{
		return telefono;
	}

	/**
	 * Method 'setTelefono'
	 * 
	 * @param telefono
	 */
	public void setTelefono(String telefono)
	{
		this.telefono = telefono;
		this.telefonoModified = true;
	}

	/** 
	 * Sets the value of telefonoModified
	 */
	public void setTelefonoModified(boolean telefonoModified)
	{
		this.telefonoModified = telefonoModified;
	}

	/** 
	 * Gets the value of telefonoModified
	 */
	public boolean isTelefonoModified()
	{
		return telefonoModified;
	}

	/**
	 * Method 'getLocalidad'
	 * 
	 * @return String
	 */
	public String getLocalidad()
	{
		return localidad;
	}

	/**
	 * Method 'setLocalidad'
	 * 
	 * @param localidad
	 */
	public void setLocalidad(String localidad)
	{
		this.localidad = localidad;
		this.localidadModified = true;
	}

	/** 
	 * Sets the value of localidadModified
	 */
	public void setLocalidadModified(boolean localidadModified)
	{
		this.localidadModified = localidadModified;
	}

	/** 
	 * Gets the value of localidadModified
	 */
	public boolean isLocalidadModified()
	{
		return localidadModified;
	}

	/**
	 * Method 'getBarrio'
	 * 
	 * @return String
	 */
	public String getBarrio()
	{
		return barrio;
	}

	/**
	 * Method 'setBarrio'
	 * 
	 * @param barrio
	 */
	public void setBarrio(String barrio)
	{
		this.barrio = barrio;
		this.barrioModified = true;
	}

	/** 
	 * Sets the value of barrioModified
	 */
	public void setBarrioModified(boolean barrioModified)
	{
		this.barrioModified = barrioModified;
	}

	/** 
	 * Gets the value of barrioModified
	 */
	public boolean isBarrioModified()
	{
		return barrioModified;
	}

	/**
	 * Method 'getCuentaTipoDocumento'
	 * 
	 * @return String
	 */
	public String getCuentaTipoDocumento()
	{
		return cuentaTipoDocumento;
	}

	/**
	 * Method 'setCuentaTipoDocumento'
	 * 
	 * @param cuentaTipoDocumento
	 */
	public void setCuentaTipoDocumento(String cuentaTipoDocumento)
	{
		this.cuentaTipoDocumento = cuentaTipoDocumento;
		this.cuentaTipoDocumentoModified = true;
	}

	/** 
	 * Sets the value of cuentaTipoDocumentoModified
	 */
	public void setCuentaTipoDocumentoModified(boolean cuentaTipoDocumentoModified)
	{
		this.cuentaTipoDocumentoModified = cuentaTipoDocumentoModified;
	}

	/** 
	 * Gets the value of cuentaTipoDocumentoModified
	 */
	public boolean isCuentaTipoDocumentoModified()
	{
		return cuentaTipoDocumentoModified;
	}

	/**
	 * Method 'getCuentaNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getCuentaNumeroDocumento()
	{
		return cuentaNumeroDocumento;
	}

	/**
	 * Method 'setCuentaNumeroDocumento'
	 * 
	 * @param cuentaNumeroDocumento
	 */
	public void setCuentaNumeroDocumento(String cuentaNumeroDocumento)
	{
		this.cuentaNumeroDocumento = cuentaNumeroDocumento;
		this.cuentaNumeroDocumentoModified = true;
	}

	/** 
	 * Sets the value of cuentaNumeroDocumentoModified
	 */
	public void setCuentaNumeroDocumentoModified(boolean cuentaNumeroDocumentoModified)
	{
		this.cuentaNumeroDocumentoModified = cuentaNumeroDocumentoModified;
	}

	/** 
	 * Gets the value of cuentaNumeroDocumentoModified
	 */
	public boolean isCuentaNumeroDocumentoModified()
	{
		return cuentaNumeroDocumentoModified;
	}

	/**
	 * Method 'getMunicipioIdmunicipio'
	 * 
	 * @return int
	 */
	public int getMunicipioIdmunicipio()
	{
		return municipioIdmunicipio;
	}

	/**
	 * Method 'setMunicipioIdmunicipio'
	 * 
	 * @param municipioIdmunicipio
	 */
	public void setMunicipioIdmunicipio(int municipioIdmunicipio)
	{
		this.municipioIdmunicipio = municipioIdmunicipio;
		this.municipioIdmunicipioModified = true;
	}

	/** 
	 * Sets the value of municipioIdmunicipioModified
	 */
	public void setMunicipioIdmunicipioModified(boolean municipioIdmunicipioModified)
	{
		this.municipioIdmunicipioModified = municipioIdmunicipioModified;
	}

	/** 
	 * Gets the value of municipioIdmunicipioModified
	 */
	public boolean isMunicipioIdmunicipioModified()
	{
		return municipioIdmunicipioModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Domicilio)) {
			return false;
		}
		
		final Domicilio _cast = (Domicilio) _other;
		if (idDOMICILIO != _cast.idDOMICILIO) {
			return false;
		}
		
		if (idDOMICILIOModified != _cast.idDOMICILIOModified) {
			return false;
		}
		
		if (dirrecion == null ? _cast.dirrecion != dirrecion : !dirrecion.equals( _cast.dirrecion )) {
			return false;
		}
		
		if (dirrecionModified != _cast.dirrecionModified) {
			return false;
		}
		
		if (telefono == null ? _cast.telefono != telefono : !telefono.equals( _cast.telefono )) {
			return false;
		}
		
		if (telefonoModified != _cast.telefonoModified) {
			return false;
		}
		
		if (localidad == null ? _cast.localidad != localidad : !localidad.equals( _cast.localidad )) {
			return false;
		}
		
		if (localidadModified != _cast.localidadModified) {
			return false;
		}
		
		if (barrio == null ? _cast.barrio != barrio : !barrio.equals( _cast.barrio )) {
			return false;
		}
		
		if (barrioModified != _cast.barrioModified) {
			return false;
		}
		
		if (cuentaTipoDocumento == null ? _cast.cuentaTipoDocumento != cuentaTipoDocumento : !cuentaTipoDocumento.equals( _cast.cuentaTipoDocumento )) {
			return false;
		}
		
		if (cuentaTipoDocumentoModified != _cast.cuentaTipoDocumentoModified) {
			return false;
		}
		
		if (cuentaNumeroDocumento == null ? _cast.cuentaNumeroDocumento != cuentaNumeroDocumento : !cuentaNumeroDocumento.equals( _cast.cuentaNumeroDocumento )) {
			return false;
		}
		
		if (cuentaNumeroDocumentoModified != _cast.cuentaNumeroDocumentoModified) {
			return false;
		}
		
		if (municipioIdmunicipio != _cast.municipioIdmunicipio) {
			return false;
		}
		
		if (municipioIdmunicipioModified != _cast.municipioIdmunicipioModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDOMICILIO;
		_hashCode = 29 * _hashCode + (idDOMICILIOModified ? 1 : 0);
		if (dirrecion != null) {
			_hashCode = 29 * _hashCode + dirrecion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (dirrecionModified ? 1 : 0);
		if (telefono != null) {
			_hashCode = 29 * _hashCode + telefono.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (telefonoModified ? 1 : 0);
		if (localidad != null) {
			_hashCode = 29 * _hashCode + localidad.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (localidadModified ? 1 : 0);
		if (barrio != null) {
			_hashCode = 29 * _hashCode + barrio.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (barrioModified ? 1 : 0);
		if (cuentaTipoDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaTipoDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (cuentaTipoDocumentoModified ? 1 : 0);
		if (cuentaNumeroDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaNumeroDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (cuentaNumeroDocumentoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + municipioIdmunicipio;
		_hashCode = 29 * _hashCode + (municipioIdmunicipioModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DomicilioPk
	 */
	public DomicilioPk createPk()
	{
		return new DomicilioPk(idDOMICILIO);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.dto.Domicilio: " );
		ret.append( "idDOMICILIO=" + idDOMICILIO );
		ret.append( ", dirrecion=" + dirrecion );
		ret.append( ", telefono=" + telefono );
		ret.append( ", localidad=" + localidad );
		ret.append( ", barrio=" + barrio );
		ret.append( ", cuentaTipoDocumento=" + cuentaTipoDocumento );
		ret.append( ", cuentaNumeroDocumento=" + cuentaNumeroDocumento );
		ret.append( ", municipioIdmunicipio=" + municipioIdmunicipio );
		return ret.toString();
	}

}
