/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the domicilio table.
 */
public class DomicilioPk implements Serializable
{
	protected int idDOMICILIO;

	/** 
	 * This attribute represents whether the primitive attribute idDOMICILIO is null.
	 */
	protected boolean idDOMICILIONull;

	/** 
	 * Sets the value of idDOMICILIO
	 */
	public void setIdDOMICILIO(int idDOMICILIO)
	{
		this.idDOMICILIO = idDOMICILIO;
	}

	/** 
	 * Gets the value of idDOMICILIO
	 */
	public int getIdDOMICILIO()
	{
		return idDOMICILIO;
	}

	/**
	 * Method 'DomicilioPk'
	 * 
	 */
	public DomicilioPk()
	{
	}

	/**
	 * Method 'DomicilioPk'
	 * 
	 * @param idDOMICILIO
	 */
	public DomicilioPk(final int idDOMICILIO)
	{
		this.idDOMICILIO = idDOMICILIO;
	}

	/** 
	 * Sets the value of idDOMICILIONull
	 */
	public void setIdDOMICILIONull(boolean idDOMICILIONull)
	{
		this.idDOMICILIONull = idDOMICILIONull;
	}

	/** 
	 * Gets the value of idDOMICILIONull
	 */
	public boolean isIdDOMICILIONull()
	{
		return idDOMICILIONull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DomicilioPk)) {
			return false;
		}
		
		final DomicilioPk _cast = (DomicilioPk) _other;
		if (idDOMICILIO != _cast.idDOMICILIO) {
			return false;
		}
		
		if (idDOMICILIONull != _cast.idDOMICILIONull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDOMICILIO;
		_hashCode = 29 * _hashCode + (idDOMICILIONull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.dto.DomicilioPk: " );
		ret.append( "idDOMICILIO=" + idDOMICILIO );
		return ret.toString();
	}

}
