/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.dto;

import edu.co.sena.dao.*;
import edu.co.sena.factory.*;
import edu.co.sena.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Inventario implements Serializable
{
	/** 
	 * This attribute maps to the column ID_INVENTARIO in the inventario table.
	 */
	protected int idInventario;

	/** 
	 * This attribute represents whether the attribute idInventario has been modified since being read from the database.
	 */
	protected boolean idInventarioModified = false;

	/** 
	 * This attribute maps to the column CANTIDAD in the inventario table.
	 */
	protected int cantidad;

	/** 
	 * This attribute represents whether the attribute cantidad has been modified since being read from the database.
	 */
	protected boolean cantidadModified = false;

	/** 
	 * This attribute maps to the column PROVEEDOR_TIPO_DOCUMENTO in the inventario table.
	 */
	protected String proveedorTipoDocumento;

	/** 
	 * This attribute represents whether the attribute proveedorTipoDocumento has been modified since being read from the database.
	 */
	protected boolean proveedorTipoDocumentoModified = false;

	/** 
	 * This attribute maps to the column PROVEEDOR_NUMERO_DOCUMENTO in the inventario table.
	 */
	protected String proveedorNumeroDocumento;

	/** 
	 * This attribute represents whether the attribute proveedorNumeroDocumento has been modified since being read from the database.
	 */
	protected boolean proveedorNumeroDocumentoModified = false;

	/** 
	 * This attribute maps to the column PRODUCTO_ID_PRODUCTO in the inventario table.
	 */
	protected String productoIdProducto;

	/** 
	 * This attribute represents whether the attribute productoIdProducto has been modified since being read from the database.
	 */
	protected boolean productoIdProductoModified = false;

	/**
	 * Method 'Inventario'
	 * 
	 */
	public Inventario()
	{
	}

	/**
	 * Method 'getIdInventario'
	 * 
	 * @return int
	 */
	public int getIdInventario()
	{
		return idInventario;
	}

	/**
	 * Method 'setIdInventario'
	 * 
	 * @param idInventario
	 */
	public void setIdInventario(int idInventario)
	{
		this.idInventario = idInventario;
		this.idInventarioModified = true;
	}

	/** 
	 * Sets the value of idInventarioModified
	 */
	public void setIdInventarioModified(boolean idInventarioModified)
	{
		this.idInventarioModified = idInventarioModified;
	}

	/** 
	 * Gets the value of idInventarioModified
	 */
	public boolean isIdInventarioModified()
	{
		return idInventarioModified;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return int
	 */
	public int getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(int cantidad)
	{
		this.cantidad = cantidad;
		this.cantidadModified = true;
	}

	/** 
	 * Sets the value of cantidadModified
	 */
	public void setCantidadModified(boolean cantidadModified)
	{
		this.cantidadModified = cantidadModified;
	}

	/** 
	 * Gets the value of cantidadModified
	 */
	public boolean isCantidadModified()
	{
		return cantidadModified;
	}

	/**
	 * Method 'getProveedorTipoDocumento'
	 * 
	 * @return String
	 */
	public String getProveedorTipoDocumento()
	{
		return proveedorTipoDocumento;
	}

	/**
	 * Method 'setProveedorTipoDocumento'
	 * 
	 * @param proveedorTipoDocumento
	 */
	public void setProveedorTipoDocumento(String proveedorTipoDocumento)
	{
		this.proveedorTipoDocumento = proveedorTipoDocumento;
		this.proveedorTipoDocumentoModified = true;
	}

	/** 
	 * Sets the value of proveedorTipoDocumentoModified
	 */
	public void setProveedorTipoDocumentoModified(boolean proveedorTipoDocumentoModified)
	{
		this.proveedorTipoDocumentoModified = proveedorTipoDocumentoModified;
	}

	/** 
	 * Gets the value of proveedorTipoDocumentoModified
	 */
	public boolean isProveedorTipoDocumentoModified()
	{
		return proveedorTipoDocumentoModified;
	}

	/**
	 * Method 'getProveedorNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getProveedorNumeroDocumento()
	{
		return proveedorNumeroDocumento;
	}

	/**
	 * Method 'setProveedorNumeroDocumento'
	 * 
	 * @param proveedorNumeroDocumento
	 */
	public void setProveedorNumeroDocumento(String proveedorNumeroDocumento)
	{
		this.proveedorNumeroDocumento = proveedorNumeroDocumento;
		this.proveedorNumeroDocumentoModified = true;
	}

	/** 
	 * Sets the value of proveedorNumeroDocumentoModified
	 */
	public void setProveedorNumeroDocumentoModified(boolean proveedorNumeroDocumentoModified)
	{
		this.proveedorNumeroDocumentoModified = proveedorNumeroDocumentoModified;
	}

	/** 
	 * Gets the value of proveedorNumeroDocumentoModified
	 */
	public boolean isProveedorNumeroDocumentoModified()
	{
		return proveedorNumeroDocumentoModified;
	}

	/**
	 * Method 'getProductoIdProducto'
	 * 
	 * @return String
	 */
	public String getProductoIdProducto()
	{
		return productoIdProducto;
	}

	/**
	 * Method 'setProductoIdProducto'
	 * 
	 * @param productoIdProducto
	 */
	public void setProductoIdProducto(String productoIdProducto)
	{
		this.productoIdProducto = productoIdProducto;
		this.productoIdProductoModified = true;
	}

	/** 
	 * Sets the value of productoIdProductoModified
	 */
	public void setProductoIdProductoModified(boolean productoIdProductoModified)
	{
		this.productoIdProductoModified = productoIdProductoModified;
	}

	/** 
	 * Gets the value of productoIdProductoModified
	 */
	public boolean isProductoIdProductoModified()
	{
		return productoIdProductoModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Inventario)) {
			return false;
		}
		
		final Inventario _cast = (Inventario) _other;
		if (idInventario != _cast.idInventario) {
			return false;
		}
		
		if (idInventarioModified != _cast.idInventarioModified) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (cantidadModified != _cast.cantidadModified) {
			return false;
		}
		
		if (proveedorTipoDocumento == null ? _cast.proveedorTipoDocumento != proveedorTipoDocumento : !proveedorTipoDocumento.equals( _cast.proveedorTipoDocumento )) {
			return false;
		}
		
		if (proveedorTipoDocumentoModified != _cast.proveedorTipoDocumentoModified) {
			return false;
		}
		
		if (proveedorNumeroDocumento == null ? _cast.proveedorNumeroDocumento != proveedorNumeroDocumento : !proveedorNumeroDocumento.equals( _cast.proveedorNumeroDocumento )) {
			return false;
		}
		
		if (proveedorNumeroDocumentoModified != _cast.proveedorNumeroDocumentoModified) {
			return false;
		}
		
		if (productoIdProducto == null ? _cast.productoIdProducto != productoIdProducto : !productoIdProducto.equals( _cast.productoIdProducto )) {
			return false;
		}
		
		if (productoIdProductoModified != _cast.productoIdProductoModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idInventario;
		_hashCode = 29 * _hashCode + (idInventarioModified ? 1 : 0);
		_hashCode = 29 * _hashCode + cantidad;
		_hashCode = 29 * _hashCode + (cantidadModified ? 1 : 0);
		if (proveedorTipoDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorTipoDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (proveedorTipoDocumentoModified ? 1 : 0);
		if (proveedorNumeroDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorNumeroDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (proveedorNumeroDocumentoModified ? 1 : 0);
		if (productoIdProducto != null) {
			_hashCode = 29 * _hashCode + productoIdProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (productoIdProductoModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InventarioPk
	 */
	public InventarioPk createPk()
	{
		return new InventarioPk(idInventario, proveedorTipoDocumento, proveedorNumeroDocumento, productoIdProducto);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.dto.Inventario: " );
		ret.append( "idInventario=" + idInventario );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", proveedorTipoDocumento=" + proveedorTipoDocumento );
		ret.append( ", proveedorNumeroDocumento=" + proveedorNumeroDocumento );
		ret.append( ", productoIdProducto=" + productoIdProducto );
		return ret.toString();
	}

}
