/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the inventario table.
 */
public class InventarioPk implements Serializable
{
	protected int idInventario;

	protected String proveedorTipoDocumento;

	protected String proveedorNumeroDocumento;

	protected String productoIdProducto;

	/** 
	 * This attribute represents whether the primitive attribute idInventario is null.
	 */
	protected boolean idInventarioNull;

	/** 
	 * Sets the value of idInventario
	 */
	public void setIdInventario(int idInventario)
	{
		this.idInventario = idInventario;
	}

	/** 
	 * Gets the value of idInventario
	 */
	public int getIdInventario()
	{
		return idInventario;
	}

	/** 
	 * Sets the value of proveedorTipoDocumento
	 */
	public void setProveedorTipoDocumento(String proveedorTipoDocumento)
	{
		this.proveedorTipoDocumento = proveedorTipoDocumento;
	}

	/** 
	 * Gets the value of proveedorTipoDocumento
	 */
	public String getProveedorTipoDocumento()
	{
		return proveedorTipoDocumento;
	}

	/** 
	 * Sets the value of proveedorNumeroDocumento
	 */
	public void setProveedorNumeroDocumento(String proveedorNumeroDocumento)
	{
		this.proveedorNumeroDocumento = proveedorNumeroDocumento;
	}

	/** 
	 * Gets the value of proveedorNumeroDocumento
	 */
	public String getProveedorNumeroDocumento()
	{
		return proveedorNumeroDocumento;
	}

	/** 
	 * Sets the value of productoIdProducto
	 */
	public void setProductoIdProducto(String productoIdProducto)
	{
		this.productoIdProducto = productoIdProducto;
	}

	/** 
	 * Gets the value of productoIdProducto
	 */
	public String getProductoIdProducto()
	{
		return productoIdProducto;
	}

	/**
	 * Method 'InventarioPk'
	 * 
	 */
	public InventarioPk()
	{
	}

	/**
	 * Method 'InventarioPk'
	 * 
	 * @param idInventario
	 * @param proveedorTipoDocumento
	 * @param proveedorNumeroDocumento
	 * @param productoIdProducto
	 */
	public InventarioPk(final int idInventario, final String proveedorTipoDocumento, final String proveedorNumeroDocumento, final String productoIdProducto)
	{
		this.idInventario = idInventario;
		this.proveedorTipoDocumento = proveedorTipoDocumento;
		this.proveedorNumeroDocumento = proveedorNumeroDocumento;
		this.productoIdProducto = productoIdProducto;
	}

	/** 
	 * Sets the value of idInventarioNull
	 */
	public void setIdInventarioNull(boolean idInventarioNull)
	{
		this.idInventarioNull = idInventarioNull;
	}

	/** 
	 * Gets the value of idInventarioNull
	 */
	public boolean isIdInventarioNull()
	{
		return idInventarioNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InventarioPk)) {
			return false;
		}
		
		final InventarioPk _cast = (InventarioPk) _other;
		if (idInventario != _cast.idInventario) {
			return false;
		}
		
		if (proveedorTipoDocumento == null ? _cast.proveedorTipoDocumento != proveedorTipoDocumento : !proveedorTipoDocumento.equals( _cast.proveedorTipoDocumento )) {
			return false;
		}
		
		if (proveedorNumeroDocumento == null ? _cast.proveedorNumeroDocumento != proveedorNumeroDocumento : !proveedorNumeroDocumento.equals( _cast.proveedorNumeroDocumento )) {
			return false;
		}
		
		if (productoIdProducto == null ? _cast.productoIdProducto != productoIdProducto : !productoIdProducto.equals( _cast.productoIdProducto )) {
			return false;
		}
		
		if (idInventarioNull != _cast.idInventarioNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idInventario;
		if (proveedorTipoDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorTipoDocumento.hashCode();
		}
		
		if (proveedorNumeroDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorNumeroDocumento.hashCode();
		}
		
		if (productoIdProducto != null) {
			_hashCode = 29 * _hashCode + productoIdProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idInventarioNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.dto.InventarioPk: " );
		ret.append( "idInventario=" + idInventario );
		ret.append( ", proveedorTipoDocumento=" + proveedorTipoDocumento );
		ret.append( ", proveedorNumeroDocumento=" + proveedorNumeroDocumento );
		ret.append( ", productoIdProducto=" + productoIdProducto );
		return ret.toString();
	}

}
