/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the item_carrito table.
 */
public class ItemCarritoPk implements Serializable
{
	protected String productoIdProducto;

	protected String carritoComprasIdcarrito;

	/** 
	 * Sets the value of productoIdProducto
	 */
	public void setProductoIdProducto(String productoIdProducto)
	{
		this.productoIdProducto = productoIdProducto;
	}

	/** 
	 * Gets the value of productoIdProducto
	 */
	public String getProductoIdProducto()
	{
		return productoIdProducto;
	}

	/** 
	 * Sets the value of carritoComprasIdcarrito
	 */
	public void setCarritoComprasIdcarrito(String carritoComprasIdcarrito)
	{
		this.carritoComprasIdcarrito = carritoComprasIdcarrito;
	}

	/** 
	 * Gets the value of carritoComprasIdcarrito
	 */
	public String getCarritoComprasIdcarrito()
	{
		return carritoComprasIdcarrito;
	}

	/**
	 * Method 'ItemCarritoPk'
	 * 
	 */
	public ItemCarritoPk()
	{
	}

	/**
	 * Method 'ItemCarritoPk'
	 * 
	 * @param productoIdProducto
	 * @param carritoComprasIdcarrito
	 */
	public ItemCarritoPk(final String productoIdProducto, final String carritoComprasIdcarrito)
	{
		this.productoIdProducto = productoIdProducto;
		this.carritoComprasIdcarrito = carritoComprasIdcarrito;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ItemCarritoPk)) {
			return false;
		}
		
		final ItemCarritoPk _cast = (ItemCarritoPk) _other;
		if (productoIdProducto == null ? _cast.productoIdProducto != productoIdProducto : !productoIdProducto.equals( _cast.productoIdProducto )) {
			return false;
		}
		
		if (carritoComprasIdcarrito == null ? _cast.carritoComprasIdcarrito != carritoComprasIdcarrito : !carritoComprasIdcarrito.equals( _cast.carritoComprasIdcarrito )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (productoIdProducto != null) {
			_hashCode = 29 * _hashCode + productoIdProducto.hashCode();
		}
		
		if (carritoComprasIdcarrito != null) {
			_hashCode = 29 * _hashCode + carritoComprasIdcarrito.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.dto.ItemCarritoPk: " );
		ret.append( "productoIdProducto=" + productoIdProducto );
		ret.append( ", carritoComprasIdcarrito=" + carritoComprasIdcarrito );
		return ret.toString();
	}

}
