/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.dto;

import edu.co.sena.dao.*;
import edu.co.sena.factory.*;
import edu.co.sena.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Pago implements Serializable
{
	/** 
	 * This attribute maps to the column TIPO_PAGO in the pago table.
	 */
	protected String tipoPago;

	/** 
	 * This attribute represents whether the attribute tipoPago has been modified since being read from the database.
	 */
	protected boolean tipoPagoModified = false;

	/** 
	 * This attribute maps to the column NUMERO_CUENTA in the pago table.
	 */
	protected String numeroCuenta;

	/** 
	 * This attribute represents whether the attribute numeroCuenta has been modified since being read from the database.
	 */
	protected boolean numeroCuentaModified = false;

	/** 
	 * This attribute maps to the column TARGETA in the pago table.
	 */
	protected String targeta;

	/** 
	 * This attribute represents whether the attribute targeta has been modified since being read from the database.
	 */
	protected boolean targetaModified = false;

	/** 
	 * This attribute maps to the column FACTURA_ID_FACTURA in the pago table.
	 */
	protected int facturaIdFactura;

	/** 
	 * This attribute represents whether the attribute facturaIdFactura has been modified since being read from the database.
	 */
	protected boolean facturaIdFacturaModified = false;

	/**
	 * Method 'Pago'
	 * 
	 */
	public Pago()
	{
	}

	/**
	 * Method 'getTipoPago'
	 * 
	 * @return String
	 */
	public String getTipoPago()
	{
		return tipoPago;
	}

	/**
	 * Method 'setTipoPago'
	 * 
	 * @param tipoPago
	 */
	public void setTipoPago(String tipoPago)
	{
		this.tipoPago = tipoPago;
		this.tipoPagoModified = true;
	}

	/** 
	 * Sets the value of tipoPagoModified
	 */
	public void setTipoPagoModified(boolean tipoPagoModified)
	{
		this.tipoPagoModified = tipoPagoModified;
	}

	/** 
	 * Gets the value of tipoPagoModified
	 */
	public boolean isTipoPagoModified()
	{
		return tipoPagoModified;
	}

	/**
	 * Method 'getNumeroCuenta'
	 * 
	 * @return String
	 */
	public String getNumeroCuenta()
	{
		return numeroCuenta;
	}

	/**
	 * Method 'setNumeroCuenta'
	 * 
	 * @param numeroCuenta
	 */
	public void setNumeroCuenta(String numeroCuenta)
	{
		this.numeroCuenta = numeroCuenta;
		this.numeroCuentaModified = true;
	}

	/** 
	 * Sets the value of numeroCuentaModified
	 */
	public void setNumeroCuentaModified(boolean numeroCuentaModified)
	{
		this.numeroCuentaModified = numeroCuentaModified;
	}

	/** 
	 * Gets the value of numeroCuentaModified
	 */
	public boolean isNumeroCuentaModified()
	{
		return numeroCuentaModified;
	}

	/**
	 * Method 'getTargeta'
	 * 
	 * @return String
	 */
	public String getTargeta()
	{
		return targeta;
	}

	/**
	 * Method 'setTargeta'
	 * 
	 * @param targeta
	 */
	public void setTargeta(String targeta)
	{
		this.targeta = targeta;
		this.targetaModified = true;
	}

	/** 
	 * Sets the value of targetaModified
	 */
	public void setTargetaModified(boolean targetaModified)
	{
		this.targetaModified = targetaModified;
	}

	/** 
	 * Gets the value of targetaModified
	 */
	public boolean isTargetaModified()
	{
		return targetaModified;
	}

	/**
	 * Method 'getFacturaIdFactura'
	 * 
	 * @return int
	 */
	public int getFacturaIdFactura()
	{
		return facturaIdFactura;
	}

	/**
	 * Method 'setFacturaIdFactura'
	 * 
	 * @param facturaIdFactura
	 */
	public void setFacturaIdFactura(int facturaIdFactura)
	{
		this.facturaIdFactura = facturaIdFactura;
		this.facturaIdFacturaModified = true;
	}

	/** 
	 * Sets the value of facturaIdFacturaModified
	 */
	public void setFacturaIdFacturaModified(boolean facturaIdFacturaModified)
	{
		this.facturaIdFacturaModified = facturaIdFacturaModified;
	}

	/** 
	 * Gets the value of facturaIdFacturaModified
	 */
	public boolean isFacturaIdFacturaModified()
	{
		return facturaIdFacturaModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Pago)) {
			return false;
		}
		
		final Pago _cast = (Pago) _other;
		if (tipoPago == null ? _cast.tipoPago != tipoPago : !tipoPago.equals( _cast.tipoPago )) {
			return false;
		}
		
		if (tipoPagoModified != _cast.tipoPagoModified) {
			return false;
		}
		
		if (numeroCuenta == null ? _cast.numeroCuenta != numeroCuenta : !numeroCuenta.equals( _cast.numeroCuenta )) {
			return false;
		}
		
		if (numeroCuentaModified != _cast.numeroCuentaModified) {
			return false;
		}
		
		if (targeta == null ? _cast.targeta != targeta : !targeta.equals( _cast.targeta )) {
			return false;
		}
		
		if (targetaModified != _cast.targetaModified) {
			return false;
		}
		
		if (facturaIdFactura != _cast.facturaIdFactura) {
			return false;
		}
		
		if (facturaIdFacturaModified != _cast.facturaIdFacturaModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoPago != null) {
			_hashCode = 29 * _hashCode + tipoPago.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (tipoPagoModified ? 1 : 0);
		if (numeroCuenta != null) {
			_hashCode = 29 * _hashCode + numeroCuenta.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (numeroCuentaModified ? 1 : 0);
		if (targeta != null) {
			_hashCode = 29 * _hashCode + targeta.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (targetaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + facturaIdFactura;
		_hashCode = 29 * _hashCode + (facturaIdFacturaModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PagoPk
	 */
	public PagoPk createPk()
	{
		return new PagoPk(facturaIdFactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.dto.Pago: " );
		ret.append( "tipoPago=" + tipoPago );
		ret.append( ", numeroCuenta=" + numeroCuenta );
		ret.append( ", targeta=" + targeta );
		ret.append( ", facturaIdFactura=" + facturaIdFactura );
		return ret.toString();
	}

}
