/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.dto;

import edu.co.sena.dao.*;
import edu.co.sena.factory.*;
import edu.co.sena.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Producto implements Serializable
{
	/** 
	 * This attribute maps to the column ID_PRODUCTO in the producto table.
	 */
	protected String idProducto;

	/** 
	 * This attribute represents whether the attribute idProducto has been modified since being read from the database.
	 */
	protected boolean idProductoModified = false;

	/** 
	 * This attribute maps to the column NOMBRE_PRODCUTO in the producto table.
	 */
	protected String nombreProdcuto;

	/** 
	 * This attribute represents whether the attribute nombreProdcuto has been modified since being read from the database.
	 */
	protected boolean nombreProdcutoModified = false;

	/** 
	 * This attribute maps to the column PRECIO in the producto table.
	 */
	protected float precio;

	/** 
	 * This attribute represents whether the attribute precio has been modified since being read from the database.
	 */
	protected boolean precioModified = false;

	/** 
	 * This attribute maps to the column IMAGEN in the producto table.
	 */
	protected byte[] imagen;

	/** 
	 * This attribute represents whether the attribute imagen has been modified since being read from the database.
	 */
	protected boolean imagenModified = false;

	/** 
	 * This attribute maps to the column CANTIDAD in the producto table.
	 */
	protected int cantidad;

	/** 
	 * This attribute represents whether the attribute cantidad has been modified since being read from the database.
	 */
	protected boolean cantidadModified = false;

	/** 
	 * This attribute maps to the column DESCRIPCION in the producto table.
	 */
	protected String descripcion;

	/** 
	 * This attribute represents whether the attribute descripcion has been modified since being read from the database.
	 */
	protected boolean descripcionModified = false;

	/** 
	 * This attribute maps to the column CATALOGO_ID_CATOLOGO in the producto table.
	 */
	protected int catalogoIdCatologo;

	/** 
	 * This attribute represents whether the attribute catalogoIdCatologo has been modified since being read from the database.
	 */
	protected boolean catalogoIdCatologoModified = false;

	/** 
	 * This attribute maps to the column CATEGORIA_ID_CATEGORIA in the producto table.
	 */
	protected int categoriaIdCategoria;

	/** 
	 * This attribute represents whether the attribute categoriaIdCategoria has been modified since being read from the database.
	 */
	protected boolean categoriaIdCategoriaModified = false;

	/**
	 * Method 'Producto'
	 * 
	 */
	public Producto()
	{
	}

	/**
	 * Method 'getIdProducto'
	 * 
	 * @return String
	 */
	public String getIdProducto()
	{
		return idProducto;
	}

	/**
	 * Method 'setIdProducto'
	 * 
	 * @param idProducto
	 */
	public void setIdProducto(String idProducto)
	{
		this.idProducto = idProducto;
		this.idProductoModified = true;
	}

	/** 
	 * Sets the value of idProductoModified
	 */
	public void setIdProductoModified(boolean idProductoModified)
	{
		this.idProductoModified = idProductoModified;
	}

	/** 
	 * Gets the value of idProductoModified
	 */
	public boolean isIdProductoModified()
	{
		return idProductoModified;
	}

	/**
	 * Method 'getNombreProdcuto'
	 * 
	 * @return String
	 */
	public String getNombreProdcuto()
	{
		return nombreProdcuto;
	}

	/**
	 * Method 'setNombreProdcuto'
	 * 
	 * @param nombreProdcuto
	 */
	public void setNombreProdcuto(String nombreProdcuto)
	{
		this.nombreProdcuto = nombreProdcuto;
		this.nombreProdcutoModified = true;
	}

	/** 
	 * Sets the value of nombreProdcutoModified
	 */
	public void setNombreProdcutoModified(boolean nombreProdcutoModified)
	{
		this.nombreProdcutoModified = nombreProdcutoModified;
	}

	/** 
	 * Gets the value of nombreProdcutoModified
	 */
	public boolean isNombreProdcutoModified()
	{
		return nombreProdcutoModified;
	}

	/**
	 * Method 'getPrecio'
	 * 
	 * @return float
	 */
	public float getPrecio()
	{
		return precio;
	}

	/**
	 * Method 'setPrecio'
	 * 
	 * @param precio
	 */
	public void setPrecio(float precio)
	{
		this.precio = precio;
		this.precioModified = true;
	}

	/** 
	 * Sets the value of precioModified
	 */
	public void setPrecioModified(boolean precioModified)
	{
		this.precioModified = precioModified;
	}

	/** 
	 * Gets the value of precioModified
	 */
	public boolean isPrecioModified()
	{
		return precioModified;
	}

	/**
	 * Method 'getImagen'
	 * 
	 * @return byte[]
	 */
	public byte[] getImagen()
	{
		return imagen;
	}

	/**
	 * Method 'setImagen'
	 * 
	 * @param imagen
	 */
	public void setImagen(byte[] imagen)
	{
		this.imagen = imagen;
		this.imagenModified = true;
	}

	/** 
	 * Sets the value of imagenModified
	 */
	public void setImagenModified(boolean imagenModified)
	{
		this.imagenModified = imagenModified;
	}

	/** 
	 * Gets the value of imagenModified
	 */
	public boolean isImagenModified()
	{
		return imagenModified;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return int
	 */
	public int getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(int cantidad)
	{
		this.cantidad = cantidad;
		this.cantidadModified = true;
	}

	/** 
	 * Sets the value of cantidadModified
	 */
	public void setCantidadModified(boolean cantidadModified)
	{
		this.cantidadModified = cantidadModified;
	}

	/** 
	 * Gets the value of cantidadModified
	 */
	public boolean isCantidadModified()
	{
		return cantidadModified;
	}

	/**
	 * Method 'getDescripcion'
	 * 
	 * @return String
	 */
	public String getDescripcion()
	{
		return descripcion;
	}

	/**
	 * Method 'setDescripcion'
	 * 
	 * @param descripcion
	 */
	public void setDescripcion(String descripcion)
	{
		this.descripcion = descripcion;
		this.descripcionModified = true;
	}

	/** 
	 * Sets the value of descripcionModified
	 */
	public void setDescripcionModified(boolean descripcionModified)
	{
		this.descripcionModified = descripcionModified;
	}

	/** 
	 * Gets the value of descripcionModified
	 */
	public boolean isDescripcionModified()
	{
		return descripcionModified;
	}

	/**
	 * Method 'getCatalogoIdCatologo'
	 * 
	 * @return int
	 */
	public int getCatalogoIdCatologo()
	{
		return catalogoIdCatologo;
	}

	/**
	 * Method 'setCatalogoIdCatologo'
	 * 
	 * @param catalogoIdCatologo
	 */
	public void setCatalogoIdCatologo(int catalogoIdCatologo)
	{
		this.catalogoIdCatologo = catalogoIdCatologo;
		this.catalogoIdCatologoModified = true;
	}

	/** 
	 * Sets the value of catalogoIdCatologoModified
	 */
	public void setCatalogoIdCatologoModified(boolean catalogoIdCatologoModified)
	{
		this.catalogoIdCatologoModified = catalogoIdCatologoModified;
	}

	/** 
	 * Gets the value of catalogoIdCatologoModified
	 */
	public boolean isCatalogoIdCatologoModified()
	{
		return catalogoIdCatologoModified;
	}

	/**
	 * Method 'getCategoriaIdCategoria'
	 * 
	 * @return int
	 */
	public int getCategoriaIdCategoria()
	{
		return categoriaIdCategoria;
	}

	/**
	 * Method 'setCategoriaIdCategoria'
	 * 
	 * @param categoriaIdCategoria
	 */
	public void setCategoriaIdCategoria(int categoriaIdCategoria)
	{
		this.categoriaIdCategoria = categoriaIdCategoria;
		this.categoriaIdCategoriaModified = true;
	}

	/** 
	 * Sets the value of categoriaIdCategoriaModified
	 */
	public void setCategoriaIdCategoriaModified(boolean categoriaIdCategoriaModified)
	{
		this.categoriaIdCategoriaModified = categoriaIdCategoriaModified;
	}

	/** 
	 * Gets the value of categoriaIdCategoriaModified
	 */
	public boolean isCategoriaIdCategoriaModified()
	{
		return categoriaIdCategoriaModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Producto)) {
			return false;
		}
		
		final Producto _cast = (Producto) _other;
		if (idProducto == null ? _cast.idProducto != idProducto : !idProducto.equals( _cast.idProducto )) {
			return false;
		}
		
		if (idProductoModified != _cast.idProductoModified) {
			return false;
		}
		
		if (nombreProdcuto == null ? _cast.nombreProdcuto != nombreProdcuto : !nombreProdcuto.equals( _cast.nombreProdcuto )) {
			return false;
		}
		
		if (nombreProdcutoModified != _cast.nombreProdcutoModified) {
			return false;
		}
		
		if (precio != _cast.precio) {
			return false;
		}
		
		if (precioModified != _cast.precioModified) {
			return false;
		}
		
		if (imagen == null ? _cast.imagen != imagen : !imagen.equals( _cast.imagen )) {
			return false;
		}
		
		if (imagenModified != _cast.imagenModified) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (cantidadModified != _cast.cantidadModified) {
			return false;
		}
		
		if (descripcion == null ? _cast.descripcion != descripcion : !descripcion.equals( _cast.descripcion )) {
			return false;
		}
		
		if (descripcionModified != _cast.descripcionModified) {
			return false;
		}
		
		if (catalogoIdCatologo != _cast.catalogoIdCatologo) {
			return false;
		}
		
		if (catalogoIdCatologoModified != _cast.catalogoIdCatologoModified) {
			return false;
		}
		
		if (categoriaIdCategoria != _cast.categoriaIdCategoria) {
			return false;
		}
		
		if (categoriaIdCategoriaModified != _cast.categoriaIdCategoriaModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idProducto != null) {
			_hashCode = 29 * _hashCode + idProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idProductoModified ? 1 : 0);
		if (nombreProdcuto != null) {
			_hashCode = 29 * _hashCode + nombreProdcuto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreProdcutoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(precio);
		_hashCode = 29 * _hashCode + (precioModified ? 1 : 0);
		if (imagen != null) {
			_hashCode = 29 * _hashCode + imagen.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (imagenModified ? 1 : 0);
		_hashCode = 29 * _hashCode + cantidad;
		_hashCode = 29 * _hashCode + (cantidadModified ? 1 : 0);
		if (descripcion != null) {
			_hashCode = 29 * _hashCode + descripcion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (descripcionModified ? 1 : 0);
		_hashCode = 29 * _hashCode + catalogoIdCatologo;
		_hashCode = 29 * _hashCode + (catalogoIdCatologoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + categoriaIdCategoria;
		_hashCode = 29 * _hashCode + (categoriaIdCategoriaModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProductoPk
	 */
	public ProductoPk createPk()
	{
		return new ProductoPk(idProducto);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.dto.Producto: " );
		ret.append( "idProducto=" + idProducto );
		ret.append( ", nombreProdcuto=" + nombreProdcuto );
		ret.append( ", precio=" + precio );
		ret.append( ", imagen=" + imagen );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", descripcion=" + descripcion );
		ret.append( ", catalogoIdCatologo=" + catalogoIdCatologo );
		ret.append( ", categoriaIdCategoria=" + categoriaIdCategoria );
		return ret.toString();
	}

}
