/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.dto;

import edu.co.sena.dao.*;
import edu.co.sena.factory.*;
import edu.co.sena.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Proveedor implements Serializable
{
	/** 
	 * This attribute maps to the column TIPO_DOCUMENTO in the proveedor table.
	 */
	protected String tipoDocumento;

	/** 
	 * This attribute represents whether the attribute tipoDocumento has been modified since being read from the database.
	 */
	protected boolean tipoDocumentoModified = false;

	/** 
	 * This attribute maps to the column NUMERO_DOCUMENTO in the proveedor table.
	 */
	protected String numeroDocumento;

	/** 
	 * This attribute represents whether the attribute numeroDocumento has been modified since being read from the database.
	 */
	protected boolean numeroDocumentoModified = false;

	/** 
	 * This attribute maps to the column NOMBRE_PROVVEDOR in the proveedor table.
	 */
	protected String nombreProvvedor;

	/** 
	 * This attribute represents whether the attribute nombreProvvedor has been modified since being read from the database.
	 */
	protected boolean nombreProvvedorModified = false;

	/** 
	 * This attribute maps to the column TELEFONO in the proveedor table.
	 */
	protected String telefono;

	/** 
	 * This attribute represents whether the attribute telefono has been modified since being read from the database.
	 */
	protected boolean telefonoModified = false;

	/** 
	 * This attribute maps to the column CORREO in the proveedor table.
	 */
	protected String correo;

	/** 
	 * This attribute represents whether the attribute correo has been modified since being read from the database.
	 */
	protected boolean correoModified = false;

	/**
	 * Method 'Proveedor'
	 * 
	 */
	public Proveedor()
	{
	}

	/**
	 * Method 'getTipoDocumento'
	 * 
	 * @return String
	 */
	public String getTipoDocumento()
	{
		return tipoDocumento;
	}

	/**
	 * Method 'setTipoDocumento'
	 * 
	 * @param tipoDocumento
	 */
	public void setTipoDocumento(String tipoDocumento)
	{
		this.tipoDocumento = tipoDocumento;
		this.tipoDocumentoModified = true;
	}

	/** 
	 * Sets the value of tipoDocumentoModified
	 */
	public void setTipoDocumentoModified(boolean tipoDocumentoModified)
	{
		this.tipoDocumentoModified = tipoDocumentoModified;
	}

	/** 
	 * Gets the value of tipoDocumentoModified
	 */
	public boolean isTipoDocumentoModified()
	{
		return tipoDocumentoModified;
	}

	/**
	 * Method 'getNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getNumeroDocumento()
	{
		return numeroDocumento;
	}

	/**
	 * Method 'setNumeroDocumento'
	 * 
	 * @param numeroDocumento
	 */
	public void setNumeroDocumento(String numeroDocumento)
	{
		this.numeroDocumento = numeroDocumento;
		this.numeroDocumentoModified = true;
	}

	/** 
	 * Sets the value of numeroDocumentoModified
	 */
	public void setNumeroDocumentoModified(boolean numeroDocumentoModified)
	{
		this.numeroDocumentoModified = numeroDocumentoModified;
	}

	/** 
	 * Gets the value of numeroDocumentoModified
	 */
	public boolean isNumeroDocumentoModified()
	{
		return numeroDocumentoModified;
	}

	/**
	 * Method 'getNombreProvvedor'
	 * 
	 * @return String
	 */
	public String getNombreProvvedor()
	{
		return nombreProvvedor;
	}

	/**
	 * Method 'setNombreProvvedor'
	 * 
	 * @param nombreProvvedor
	 */
	public void setNombreProvvedor(String nombreProvvedor)
	{
		this.nombreProvvedor = nombreProvvedor;
		this.nombreProvvedorModified = true;
	}

	/** 
	 * Sets the value of nombreProvvedorModified
	 */
	public void setNombreProvvedorModified(boolean nombreProvvedorModified)
	{
		this.nombreProvvedorModified = nombreProvvedorModified;
	}

	/** 
	 * Gets the value of nombreProvvedorModified
	 */
	public boolean isNombreProvvedorModified()
	{
		return nombreProvvedorModified;
	}

	/**
	 * Method 'getTelefono'
	 * 
	 * @return String
	 */
	public String getTelefono()
	{
		return telefono;
	}

	/**
	 * Method 'setTelefono'
	 * 
	 * @param telefono
	 */
	public void setTelefono(String telefono)
	{
		this.telefono = telefono;
		this.telefonoModified = true;
	}

	/** 
	 * Sets the value of telefonoModified
	 */
	public void setTelefonoModified(boolean telefonoModified)
	{
		this.telefonoModified = telefonoModified;
	}

	/** 
	 * Gets the value of telefonoModified
	 */
	public boolean isTelefonoModified()
	{
		return telefonoModified;
	}

	/**
	 * Method 'getCorreo'
	 * 
	 * @return String
	 */
	public String getCorreo()
	{
		return correo;
	}

	/**
	 * Method 'setCorreo'
	 * 
	 * @param correo
	 */
	public void setCorreo(String correo)
	{
		this.correo = correo;
		this.correoModified = true;
	}

	/** 
	 * Sets the value of correoModified
	 */
	public void setCorreoModified(boolean correoModified)
	{
		this.correoModified = correoModified;
	}

	/** 
	 * Gets the value of correoModified
	 */
	public boolean isCorreoModified()
	{
		return correoModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Proveedor)) {
			return false;
		}
		
		final Proveedor _cast = (Proveedor) _other;
		if (tipoDocumento == null ? _cast.tipoDocumento != tipoDocumento : !tipoDocumento.equals( _cast.tipoDocumento )) {
			return false;
		}
		
		if (tipoDocumentoModified != _cast.tipoDocumentoModified) {
			return false;
		}
		
		if (numeroDocumento == null ? _cast.numeroDocumento != numeroDocumento : !numeroDocumento.equals( _cast.numeroDocumento )) {
			return false;
		}
		
		if (numeroDocumentoModified != _cast.numeroDocumentoModified) {
			return false;
		}
		
		if (nombreProvvedor == null ? _cast.nombreProvvedor != nombreProvvedor : !nombreProvvedor.equals( _cast.nombreProvvedor )) {
			return false;
		}
		
		if (nombreProvvedorModified != _cast.nombreProvvedorModified) {
			return false;
		}
		
		if (telefono == null ? _cast.telefono != telefono : !telefono.equals( _cast.telefono )) {
			return false;
		}
		
		if (telefonoModified != _cast.telefonoModified) {
			return false;
		}
		
		if (correo == null ? _cast.correo != correo : !correo.equals( _cast.correo )) {
			return false;
		}
		
		if (correoModified != _cast.correoModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (tipoDocumentoModified ? 1 : 0);
		if (numeroDocumento != null) {
			_hashCode = 29 * _hashCode + numeroDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (numeroDocumentoModified ? 1 : 0);
		if (nombreProvvedor != null) {
			_hashCode = 29 * _hashCode + nombreProvvedor.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreProvvedorModified ? 1 : 0);
		if (telefono != null) {
			_hashCode = 29 * _hashCode + telefono.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (telefonoModified ? 1 : 0);
		if (correo != null) {
			_hashCode = 29 * _hashCode + correo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (correoModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProveedorPk
	 */
	public ProveedorPk createPk()
	{
		return new ProveedorPk(tipoDocumento, numeroDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.dto.Proveedor: " );
		ret.append( "tipoDocumento=" + tipoDocumento );
		ret.append( ", numeroDocumento=" + numeroDocumento );
		ret.append( ", nombreProvvedor=" + nombreProvvedor );
		ret.append( ", telefono=" + telefono );
		ret.append( ", correo=" + correo );
		return ret.toString();
	}

}
