/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.negocio.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.dao.DomicilioDao;
import edu.co.sena.dto.Domicilio;
import edu.co.sena.exceptions.DomicilioDaoException;
import edu.co.sena.factory.DomicilioDaoFactory;

public class DomicilioDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByCuenta("", "");
		// findByMunicipio(0);
		// findWhereIdDOMICILIOEquals(0);
		// findWhereDirrecionEquals("");
		// findWhereTelefonoEquals("");
		// findWhereLocalidadEquals("");
		// findWhereBarrioEquals("");
		// findWhereCuentaTipoDocumentoEquals("");
		// findWhereCuentaNumeroDocumentoEquals("");
		// findWhereMunicipioIdmunicipioEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			DomicilioDao _dao = getDomicilioDao();
			Domicilio _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByCuenta'
	 * 
	 * @param cuentaTipoDocumento
	 * @param cuentaNumeroDocumento
	 */
	public static void findByCuenta(String cuentaTipoDocumento, String cuentaNumeroDocumento)
	{
		try {
			DomicilioDao _dao = getDomicilioDao();
			Domicilio _result[] = _dao.findByCuenta(cuentaTipoDocumento, cuentaNumeroDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByMunicipio'
	 * 
	 * @param municipioIdmunicipio
	 */
	public static void findByMunicipio(int municipioIdmunicipio)
	{
		try {
			DomicilioDao _dao = getDomicilioDao();
			Domicilio _result[] = _dao.findByMunicipio(municipioIdmunicipio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdDOMICILIOEquals'
	 * 
	 * @param idDOMICILIO
	 */
	public static void findWhereIdDOMICILIOEquals(int idDOMICILIO)
	{
		try {
			DomicilioDao _dao = getDomicilioDao();
			Domicilio _result[] = _dao.findWhereIdDOMICILIOEquals(idDOMICILIO);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDirrecionEquals'
	 * 
	 * @param dirrecion
	 */
	public static void findWhereDirrecionEquals(String dirrecion)
	{
		try {
			DomicilioDao _dao = getDomicilioDao();
			Domicilio _result[] = _dao.findWhereDirrecionEquals(dirrecion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTelefonoEquals'
	 * 
	 * @param telefono
	 */
	public static void findWhereTelefonoEquals(String telefono)
	{
		try {
			DomicilioDao _dao = getDomicilioDao();
			Domicilio _result[] = _dao.findWhereTelefonoEquals(telefono);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLocalidadEquals'
	 * 
	 * @param localidad
	 */
	public static void findWhereLocalidadEquals(String localidad)
	{
		try {
			DomicilioDao _dao = getDomicilioDao();
			Domicilio _result[] = _dao.findWhereLocalidadEquals(localidad);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereBarrioEquals'
	 * 
	 * @param barrio
	 */
	public static void findWhereBarrioEquals(String barrio)
	{
		try {
			DomicilioDao _dao = getDomicilioDao();
			Domicilio _result[] = _dao.findWhereBarrioEquals(barrio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCuentaTipoDocumentoEquals'
	 * 
	 * @param cuentaTipoDocumento
	 */
	public static void findWhereCuentaTipoDocumentoEquals(String cuentaTipoDocumento)
	{
		try {
			DomicilioDao _dao = getDomicilioDao();
			Domicilio _result[] = _dao.findWhereCuentaTipoDocumentoEquals(cuentaTipoDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCuentaNumeroDocumentoEquals'
	 * 
	 * @param cuentaNumeroDocumento
	 */
	public static void findWhereCuentaNumeroDocumentoEquals(String cuentaNumeroDocumento)
	{
		try {
			DomicilioDao _dao = getDomicilioDao();
			Domicilio _result[] = _dao.findWhereCuentaNumeroDocumentoEquals(cuentaNumeroDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereMunicipioIdmunicipioEquals'
	 * 
	 * @param municipioIdmunicipio
	 */
	public static void findWhereMunicipioIdmunicipioEquals(int municipioIdmunicipio)
	{
		try {
			DomicilioDao _dao = getDomicilioDao();
			Domicilio _result[] = _dao.findWhereMunicipioIdmunicipioEquals(municipioIdmunicipio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getDomicilioDao'
	 * 
	 * @return DomicilioDao
	 */
	public static DomicilioDao getDomicilioDao()
	{
		return DomicilioDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Domicilio dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdDOMICILIO() );
		buf.append( ", " );
		buf.append( dto.getDirrecion() );
		buf.append( ", " );
		buf.append( dto.getTelefono() );
		buf.append( ", " );
		buf.append( dto.getLocalidad() );
		buf.append( ", " );
		buf.append( dto.getBarrio() );
		buf.append( ", " );
		buf.append( dto.getCuentaTipoDocumento() );
		buf.append( ", " );
		buf.append( dto.getCuentaNumeroDocumento() );
		buf.append( ", " );
		buf.append( dto.getMunicipioIdmunicipio() );
		System.out.println( buf.toString() );
	}

}
