/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.jdbc;

import edu.co.sena.dao.*;
import edu.co.sena.factory.*;
import edu.co.sena.dto.*;
import edu.co.sena.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import org.apache.log4j.Logger;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class InventarioDaoImpl extends AbstractDAO implements InventarioDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	protected static final Logger logger = Logger.getLogger( InventarioDaoImpl.class );

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_INVENTARIO, CANTIDAD, PROVEEDOR_TIPO_DOCUMENTO, PROVEEDOR_NUMERO_DOCUMENTO, PRODUCTO_ID_PRODUCTO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_INVENTARIO, CANTIDAD, PROVEEDOR_TIPO_DOCUMENTO, PROVEEDOR_NUMERO_DOCUMENTO, PRODUCTO_ID_PRODUCTO ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_INVENTARIO = ?, CANTIDAD = ?, PROVEEDOR_TIPO_DOCUMENTO = ?, PROVEEDOR_NUMERO_DOCUMENTO = ?, PRODUCTO_ID_PRODUCTO = ? WHERE ID_INVENTARIO = ? AND PROVEEDOR_TIPO_DOCUMENTO = ? AND PROVEEDOR_NUMERO_DOCUMENTO = ? AND PRODUCTO_ID_PRODUCTO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_INVENTARIO = ? AND PROVEEDOR_TIPO_DOCUMENTO = ? AND PROVEEDOR_NUMERO_DOCUMENTO = ? AND PRODUCTO_ID_PRODUCTO = ?";

	/** 
	 * Index of column ID_INVENTARIO
	 */
	protected static final int COLUMN_ID_INVENTARIO = 1;

	/** 
	 * Index of column CANTIDAD
	 */
	protected static final int COLUMN_CANTIDAD = 2;

	/** 
	 * Index of column PROVEEDOR_TIPO_DOCUMENTO
	 */
	protected static final int COLUMN_PROVEEDOR_TIPO_DOCUMENTO = 3;

	/** 
	 * Index of column PROVEEDOR_NUMERO_DOCUMENTO
	 */
	protected static final int COLUMN_PROVEEDOR_NUMERO_DOCUMENTO = 4;

	/** 
	 * Index of column PRODUCTO_ID_PRODUCTO
	 */
	protected static final int COLUMN_PRODUCTO_ID_PRODUCTO = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column ID_INVENTARIO
	 */
	protected static final int PK_COLUMN_ID_INVENTARIO = 1;

	/** 
	 * Index of primary-key column PROVEEDOR_TIPO_DOCUMENTO
	 */
	protected static final int PK_COLUMN_PROVEEDOR_TIPO_DOCUMENTO = 2;

	/** 
	 * Index of primary-key column PROVEEDOR_NUMERO_DOCUMENTO
	 */
	protected static final int PK_COLUMN_PROVEEDOR_NUMERO_DOCUMENTO = 3;

	/** 
	 * Index of primary-key column PRODUCTO_ID_PRODUCTO
	 */
	protected static final int PK_COLUMN_PRODUCTO_ID_PRODUCTO = 4;

	/** 
	 * Inserts a new row in the inventario table.
	 */
	public InventarioPk insert(Inventario dto) throws InventarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdInventarioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_INVENTARIO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCantidadModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "CANTIDAD" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isProveedorTipoDocumentoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "PROVEEDOR_TIPO_DOCUMENTO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isProveedorNumeroDocumentoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "PROVEEDOR_NUMERO_DOCUMENTO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isProductoIdProductoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "PRODUCTO_ID_PRODUCTO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdInventarioModified()) {
				stmt.setInt( index++, dto.getIdInventario() );
			}
		
			if (dto.isCantidadModified()) {
				stmt.setInt( index++, dto.getCantidad() );
			}
		
			if (dto.isProveedorTipoDocumentoModified()) {
				stmt.setString( index++, dto.getProveedorTipoDocumento() );
			}
		
			if (dto.isProveedorNumeroDocumentoModified()) {
				stmt.setString( index++, dto.getProveedorNumeroDocumento() );
			}
		
			if (dto.isProductoIdProductoModified()) {
				stmt.setString( index++, dto.getProductoIdProducto() );
			}
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new InventarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the inventario table.
	 */
	public void update(InventarioPk pk, Inventario dto) throws InventarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdInventarioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_INVENTARIO=?" );
				modified=true;
			}
		
			if (dto.isCantidadModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "CANTIDAD=?" );
				modified=true;
			}
		
			if (dto.isProveedorTipoDocumentoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "PROVEEDOR_TIPO_DOCUMENTO=?" );
				modified=true;
			}
		
			if (dto.isProveedorNumeroDocumentoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "PROVEEDOR_NUMERO_DOCUMENTO=?" );
				modified=true;
			}
		
			if (dto.isProductoIdProductoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "PRODUCTO_ID_PRODUCTO=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE ID_INVENTARIO=? AND PROVEEDOR_TIPO_DOCUMENTO=? AND PROVEEDOR_NUMERO_DOCUMENTO=? AND PRODUCTO_ID_PRODUCTO=?" );
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdInventarioModified()) {
				stmt.setInt( index++, dto.getIdInventario() );
			}
		
			if (dto.isCantidadModified()) {
				stmt.setInt( index++, dto.getCantidad() );
			}
		
			if (dto.isProveedorTipoDocumentoModified()) {
				stmt.setString( index++, dto.getProveedorTipoDocumento() );
			}
		
			if (dto.isProveedorNumeroDocumentoModified()) {
				stmt.setString( index++, dto.getProveedorNumeroDocumento() );
			}
		
			if (dto.isProductoIdProductoModified()) {
				stmt.setString( index++, dto.getProductoIdProducto() );
			}
		
			stmt.setInt( index++, pk.getIdInventario() );
			stmt.setString( index++, pk.getProveedorTipoDocumento() );
			stmt.setString( index++, pk.getProveedorNumeroDocumento() );
			stmt.setString( index++, pk.getProductoIdProducto() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new InventarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the inventario table.
	 */
	public void delete(InventarioPk pk) throws InventarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_DELETE + " with PK: " + pk);
			}
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdInventario() );
			stmt.setString( 2, pk.getProveedorTipoDocumento() );
			stmt.setString( 3, pk.getProveedorNumeroDocumento() );
			stmt.setString( 4, pk.getProductoIdProducto() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new InventarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the inventario table that matches the specified primary-key value.
	 */
	public Inventario findByPrimaryKey(InventarioPk pk) throws InventarioDaoException
	{
		return findByPrimaryKey( pk.getIdInventario(), pk.getProveedorTipoDocumento(), pk.getProveedorNumeroDocumento(), pk.getProductoIdProducto() );
	}

	/** 
	 * Returns all rows from the inventario table that match the criteria 'ID_INVENTARIO = :idInventario AND PROVEEDOR_TIPO_DOCUMENTO = :proveedorTipoDocumento AND PROVEEDOR_NUMERO_DOCUMENTO = :proveedorNumeroDocumento AND PRODUCTO_ID_PRODUCTO = :productoIdProducto'.
	 */
	public Inventario findByPrimaryKey(int idInventario, String proveedorTipoDocumento, String proveedorNumeroDocumento, String productoIdProducto) throws InventarioDaoException
	{
		Inventario ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_INVENTARIO = ? AND PROVEEDOR_TIPO_DOCUMENTO = ? AND PROVEEDOR_NUMERO_DOCUMENTO = ? AND PRODUCTO_ID_PRODUCTO = ?", new Object[] {  new Integer(idInventario), proveedorTipoDocumento, proveedorNumeroDocumento, productoIdProducto } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the inventario table that match the criteria ''.
	 */
	public Inventario[] findAll() throws InventarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_INVENTARIO, PROVEEDOR_TIPO_DOCUMENTO, PROVEEDOR_NUMERO_DOCUMENTO, PRODUCTO_ID_PRODUCTO", null );
	}

	/** 
	 * Returns all rows from the inventario table that match the criteria 'PRODUCTO_ID_PRODUCTO = :productoIdProducto'.
	 */
	public Inventario[] findByProducto(String productoIdProducto) throws InventarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PRODUCTO_ID_PRODUCTO = ?", new Object[] { productoIdProducto } );
	}

	/** 
	 * Returns all rows from the inventario table that match the criteria 'PROVEEDOR_TIPO_DOCUMENTO = :proveedorTipoDocumento AND PROVEEDOR_NUMERO_DOCUMENTO = :proveedorNumeroDocumento'.
	 */
	public Inventario[] findByProveedor(String proveedorTipoDocumento, String proveedorNumeroDocumento) throws InventarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PROVEEDOR_TIPO_DOCUMENTO = ? AND PROVEEDOR_NUMERO_DOCUMENTO = ?", new Object[] { proveedorTipoDocumento, proveedorNumeroDocumento } );
	}

	/** 
	 * Returns all rows from the inventario table that match the criteria 'ID_INVENTARIO = :idInventario'.
	 */
	public Inventario[] findWhereIdInventarioEquals(int idInventario) throws InventarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_INVENTARIO = ? ORDER BY ID_INVENTARIO", new Object[] {  new Integer(idInventario) } );
	}

	/** 
	 * Returns all rows from the inventario table that match the criteria 'CANTIDAD = :cantidad'.
	 */
	public Inventario[] findWhereCantidadEquals(int cantidad) throws InventarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CANTIDAD = ? ORDER BY CANTIDAD", new Object[] {  new Integer(cantidad) } );
	}

	/** 
	 * Returns all rows from the inventario table that match the criteria 'PROVEEDOR_TIPO_DOCUMENTO = :proveedorTipoDocumento'.
	 */
	public Inventario[] findWhereProveedorTipoDocumentoEquals(String proveedorTipoDocumento) throws InventarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PROVEEDOR_TIPO_DOCUMENTO = ? ORDER BY PROVEEDOR_TIPO_DOCUMENTO", new Object[] { proveedorTipoDocumento } );
	}

	/** 
	 * Returns all rows from the inventario table that match the criteria 'PROVEEDOR_NUMERO_DOCUMENTO = :proveedorNumeroDocumento'.
	 */
	public Inventario[] findWhereProveedorNumeroDocumentoEquals(String proveedorNumeroDocumento) throws InventarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PROVEEDOR_NUMERO_DOCUMENTO = ? ORDER BY PROVEEDOR_NUMERO_DOCUMENTO", new Object[] { proveedorNumeroDocumento } );
	}

	/** 
	 * Returns all rows from the inventario table that match the criteria 'PRODUCTO_ID_PRODUCTO = :productoIdProducto'.
	 */
	public Inventario[] findWhereProductoIdProductoEquals(String productoIdProducto) throws InventarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PRODUCTO_ID_PRODUCTO = ? ORDER BY PRODUCTO_ID_PRODUCTO", new Object[] { productoIdProducto } );
	}

	/**
	 * Method 'InventarioDaoImpl'
	 * 
	 */
	public InventarioDaoImpl()
	{
	}

	/**
	 * Method 'InventarioDaoImpl'
	 * 
	 * @param userConn
	 */
	public InventarioDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "tennisshop.inventario";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Inventario fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Inventario dto = new Inventario();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Inventario[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Inventario dto = new Inventario();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Inventario ret[] = new Inventario[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Inventario dto, ResultSet rs) throws SQLException
	{
		dto.setIdInventario( rs.getInt( COLUMN_ID_INVENTARIO ) );
		dto.setCantidad( rs.getInt( COLUMN_CANTIDAD ) );
		dto.setProveedorTipoDocumento( rs.getString( COLUMN_PROVEEDOR_TIPO_DOCUMENTO ) );
		dto.setProveedorNumeroDocumento( rs.getString( COLUMN_PROVEEDOR_NUMERO_DOCUMENTO ) );
		dto.setProductoIdProducto( rs.getString( COLUMN_PRODUCTO_ID_PRODUCTO ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Inventario dto)
	{
		dto.setIdInventarioModified( false );
		dto.setCantidadModified( false );
		dto.setProveedorTipoDocumentoModified( false );
		dto.setProveedorNumeroDocumentoModified( false );
		dto.setProductoIdProductoModified( false );
	}

	/** 
	 * Returns all rows from the inventario table that match the specified arbitrary SQL statement
	 */
	public Inventario[] findByDynamicSelect(String sql, Object[] sqlParams) throws InventarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new InventarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the inventario table that match the specified arbitrary SQL statement
	 */
	public Inventario[] findByDynamicWhere(String sql, Object[] sqlParams) throws InventarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new InventarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
