/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.jdbc;

import edu.co.sena.dao.*;
import edu.co.sena.factory.*;
import edu.co.sena.dto.*;
import edu.co.sena.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import org.apache.log4j.Logger;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ProductoDaoImpl extends AbstractDAO implements ProductoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	protected static final Logger logger = Logger.getLogger( ProductoDaoImpl.class );

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_PRODUCTO, NOMBRE_PRODCUTO, PRECIO, IMAGEN, CANTIDAD, DESCRIPCION, CATALOGO_ID_CATOLOGO, CATEGORIA_ID_CATEGORIA FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_PRODUCTO, NOMBRE_PRODCUTO, PRECIO, IMAGEN, CANTIDAD, DESCRIPCION, CATALOGO_ID_CATOLOGO, CATEGORIA_ID_CATEGORIA ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_PRODUCTO = ?, NOMBRE_PRODCUTO = ?, PRECIO = ?, IMAGEN = ?, CANTIDAD = ?, DESCRIPCION = ?, CATALOGO_ID_CATOLOGO = ?, CATEGORIA_ID_CATEGORIA = ? WHERE ID_PRODUCTO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_PRODUCTO = ?";

	/** 
	 * Index of column ID_PRODUCTO
	 */
	protected static final int COLUMN_ID_PRODUCTO = 1;

	/** 
	 * Index of column NOMBRE_PRODCUTO
	 */
	protected static final int COLUMN_NOMBRE_PRODCUTO = 2;

	/** 
	 * Index of column PRECIO
	 */
	protected static final int COLUMN_PRECIO = 3;

	/** 
	 * Index of column IMAGEN
	 */
	protected static final int COLUMN_IMAGEN = 4;

	/** 
	 * Index of column CANTIDAD
	 */
	protected static final int COLUMN_CANTIDAD = 5;

	/** 
	 * Index of column DESCRIPCION
	 */
	protected static final int COLUMN_DESCRIPCION = 6;

	/** 
	 * Index of column CATALOGO_ID_CATOLOGO
	 */
	protected static final int COLUMN_CATALOGO_ID_CATOLOGO = 7;

	/** 
	 * Index of column CATEGORIA_ID_CATEGORIA
	 */
	protected static final int COLUMN_CATEGORIA_ID_CATEGORIA = 8;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 8;

	/** 
	 * Index of primary-key column ID_PRODUCTO
	 */
	protected static final int PK_COLUMN_ID_PRODUCTO = 1;

	/** 
	 * Inserts a new row in the producto table.
	 */
	public ProductoPk insert(Producto dto) throws ProductoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdProductoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_PRODUCTO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isNombreProdcutoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "NOMBRE_PRODCUTO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isPrecioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "PRECIO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isImagenModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "IMAGEN" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCantidadModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "CANTIDAD" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isDescripcionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "DESCRIPCION" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCatalogoIdCatologoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "CATALOGO_ID_CATOLOGO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCategoriaIdCategoriaModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "CATEGORIA_ID_CATEGORIA" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdProductoModified()) {
				stmt.setString( index++, dto.getIdProducto() );
			}
		
			if (dto.isNombreProdcutoModified()) {
				stmt.setString( index++, dto.getNombreProdcuto() );
			}
		
			if (dto.isPrecioModified()) {
				stmt.setFloat( index++, dto.getPrecio() );
			}
		
			if (dto.isImagenModified()) {
				super.setBlobColumn(stmt, index++, dto.getImagen() );
			}
		
			if (dto.isCantidadModified()) {
				stmt.setInt( index++, dto.getCantidad() );
			}
		
			if (dto.isDescripcionModified()) {
				stmt.setString( index++, dto.getDescripcion() );
			}
		
			if (dto.isCatalogoIdCatologoModified()) {
				stmt.setInt( index++, dto.getCatalogoIdCatologo() );
			}
		
			if (dto.isCategoriaIdCategoriaModified()) {
				stmt.setInt( index++, dto.getCategoriaIdCategoria() );
			}
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ProductoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the producto table.
	 */
	public void update(ProductoPk pk, Producto dto) throws ProductoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdProductoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_PRODUCTO=?" );
				modified=true;
			}
		
			if (dto.isNombreProdcutoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "NOMBRE_PRODCUTO=?" );
				modified=true;
			}
		
			if (dto.isPrecioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "PRECIO=?" );
				modified=true;
			}
		
			if (dto.isImagenModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "IMAGEN=?" );
				modified=true;
			}
		
			if (dto.isCantidadModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "CANTIDAD=?" );
				modified=true;
			}
		
			if (dto.isDescripcionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "DESCRIPCION=?" );
				modified=true;
			}
		
			if (dto.isCatalogoIdCatologoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "CATALOGO_ID_CATOLOGO=?" );
				modified=true;
			}
		
			if (dto.isCategoriaIdCategoriaModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "CATEGORIA_ID_CATEGORIA=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE ID_PRODUCTO=?" );
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdProductoModified()) {
				stmt.setString( index++, dto.getIdProducto() );
			}
		
			if (dto.isNombreProdcutoModified()) {
				stmt.setString( index++, dto.getNombreProdcuto() );
			}
		
			if (dto.isPrecioModified()) {
				stmt.setFloat( index++, dto.getPrecio() );
			}
		
			if (dto.isImagenModified()) {
				super.setBlobColumn(stmt, index++, dto.getImagen() );
			}
		
			if (dto.isCantidadModified()) {
				stmt.setInt( index++, dto.getCantidad() );
			}
		
			if (dto.isDescripcionModified()) {
				stmt.setString( index++, dto.getDescripcion() );
			}
		
			if (dto.isCatalogoIdCatologoModified()) {
				stmt.setInt( index++, dto.getCatalogoIdCatologo() );
			}
		
			if (dto.isCategoriaIdCategoriaModified()) {
				stmt.setInt( index++, dto.getCategoriaIdCategoria() );
			}
		
			stmt.setString( index++, pk.getIdProducto() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ProductoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the producto table.
	 */
	public void delete(ProductoPk pk) throws ProductoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_DELETE + " with PK: " + pk);
			}
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getIdProducto() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ProductoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the producto table that matches the specified primary-key value.
	 */
	public Producto findByPrimaryKey(ProductoPk pk) throws ProductoDaoException
	{
		return findByPrimaryKey( pk.getIdProducto() );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'ID_PRODUCTO = :idProducto'.
	 */
	public Producto findByPrimaryKey(String idProducto) throws ProductoDaoException
	{
		Producto ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_PRODUCTO = ?", new Object[] { idProducto } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the producto table that match the criteria ''.
	 */
	public Producto[] findAll() throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_PRODUCTO", null );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'CATALOGO_ID_CATOLOGO = :catalogoIdCatologo'.
	 */
	public Producto[] findByCatalogo(int catalogoIdCatologo) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CATALOGO_ID_CATOLOGO = ?", new Object[] {  new Integer(catalogoIdCatologo) } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'CATEGORIA_ID_CATEGORIA = :categoriaIdCategoria'.
	 */
	public Producto[] findByCategoria(int categoriaIdCategoria) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CATEGORIA_ID_CATEGORIA = ?", new Object[] {  new Integer(categoriaIdCategoria) } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'ID_PRODUCTO = :idProducto'.
	 */
	public Producto[] findWhereIdProductoEquals(String idProducto) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_PRODUCTO = ? ORDER BY ID_PRODUCTO", new Object[] { idProducto } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'NOMBRE_PRODCUTO = :nombreProdcuto'.
	 */
	public Producto[] findWhereNombreProdcutoEquals(String nombreProdcuto) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NOMBRE_PRODCUTO = ? ORDER BY NOMBRE_PRODCUTO", new Object[] { nombreProdcuto } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'PRECIO = :precio'.
	 */
	public Producto[] findWherePrecioEquals(float precio) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PRECIO = ? ORDER BY PRECIO", new Object[] {  new Float(precio) } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'IMAGEN = :imagen'.
	 */
	public Producto[] findWhereImagenEquals(byte[] imagen) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IMAGEN = ? ORDER BY IMAGEN", new Object[] { imagen } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'CANTIDAD = :cantidad'.
	 */
	public Producto[] findWhereCantidadEquals(int cantidad) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CANTIDAD = ? ORDER BY CANTIDAD", new Object[] {  new Integer(cantidad) } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'DESCRIPCION = :descripcion'.
	 */
	public Producto[] findWhereDescripcionEquals(String descripcion) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DESCRIPCION = ? ORDER BY DESCRIPCION", new Object[] { descripcion } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'CATALOGO_ID_CATOLOGO = :catalogoIdCatologo'.
	 */
	public Producto[] findWhereCatalogoIdCatologoEquals(int catalogoIdCatologo) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CATALOGO_ID_CATOLOGO = ? ORDER BY CATALOGO_ID_CATOLOGO", new Object[] {  new Integer(catalogoIdCatologo) } );
	}

	/** 
	 * Returns all rows from the producto table that match the criteria 'CATEGORIA_ID_CATEGORIA = :categoriaIdCategoria'.
	 */
	public Producto[] findWhereCategoriaIdCategoriaEquals(int categoriaIdCategoria) throws ProductoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CATEGORIA_ID_CATEGORIA = ? ORDER BY CATEGORIA_ID_CATEGORIA", new Object[] {  new Integer(categoriaIdCategoria) } );
	}

	/**
	 * Method 'ProductoDaoImpl'
	 * 
	 */
	public ProductoDaoImpl()
	{
	}

	/**
	 * Method 'ProductoDaoImpl'
	 * 
	 * @param userConn
	 */
	public ProductoDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "tennisshop.producto";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Producto fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Producto dto = new Producto();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Producto[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Producto dto = new Producto();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Producto ret[] = new Producto[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Producto dto, ResultSet rs) throws SQLException
	{
		dto.setIdProducto( rs.getString( COLUMN_ID_PRODUCTO ) );
		dto.setNombreProdcuto( rs.getString( COLUMN_NOMBRE_PRODCUTO ) );
		dto.setPrecio( rs.getFloat( COLUMN_PRECIO ) );
		dto.setImagen( super.getBlobColumn(rs, COLUMN_IMAGEN ) );
		dto.setCantidad( rs.getInt( COLUMN_CANTIDAD ) );
		dto.setDescripcion( rs.getString( COLUMN_DESCRIPCION ) );
		dto.setCatalogoIdCatologo( rs.getInt( COLUMN_CATALOGO_ID_CATOLOGO ) );
		dto.setCategoriaIdCategoria( rs.getInt( COLUMN_CATEGORIA_ID_CATEGORIA ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Producto dto)
	{
		dto.setIdProductoModified( false );
		dto.setNombreProdcutoModified( false );
		dto.setPrecioModified( false );
		dto.setImagenModified( false );
		dto.setCantidadModified( false );
		dto.setDescripcionModified( false );
		dto.setCatalogoIdCatologoModified( false );
		dto.setCategoriaIdCategoriaModified( false );
	}

	/** 
	 * Returns all rows from the producto table that match the specified arbitrary SQL statement
	 */
	public Producto[] findByDynamicSelect(String sql, Object[] sqlParams) throws ProductoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ProductoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the producto table that match the specified arbitrary SQL statement
	 */
	public Producto[] findByDynamicWhere(String sql, Object[] sqlParams) throws ProductoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ProductoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
