/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.negocio.example2;

import edu.co.sena.negocio.example.*;
import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.dao.CarritoComprasDao;
import edu.co.sena.dto.CarritoCompras;
import edu.co.sena.exceptions.CarritoComprasDaoException;
import edu.co.sena.factory.CarritoComprasDaoFactory;

public class CarritoComprasDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		 findAll();
		// findWhereIdCARRITOEquals("");
		// findWhereTotalEquals(0);
		// findWhereSubtotalEquals(0);
		// findWhereImpuestosEquals(0);
            CarritoCompras c1= new CarritoCompras();
            c1.setIdCARRITO("152589623423351741156568998");
            c1.setImpuestos(0);
            c1.setSubtotal(0);
            c1.setTotal(0);
            
       CarritoComprasDao Daocarrito1=getCarritoComprasDao();
       Daocarrito1.insert(c1);
       findAll();
            System.out.println("----------------");
            
            Daocarrito1.delete(c1.createPk());
            findAll();
            System.out.println("-----------");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			CarritoComprasDao _dao = getCarritoComprasDao();
			CarritoCompras _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdCARRITOEquals'
	 * 
	 * @param idCARRITO
	 */
	public static void findWhereIdCARRITOEquals(String idCARRITO)
	{
		try {
			CarritoComprasDao _dao = getCarritoComprasDao();
			CarritoCompras _result[] = _dao.findWhereIdCARRITOEquals(idCARRITO);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTotalEquals'
	 * 
	 * @param total
	 */
	public static void findWhereTotalEquals(double total)
	{
		try {
			CarritoComprasDao _dao = getCarritoComprasDao();
			CarritoCompras _result[] = _dao.findWhereTotalEquals(total);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSubtotalEquals'
	 * 
	 * @param subtotal
	 */
	public static void findWhereSubtotalEquals(double subtotal)
	{
		try {
			CarritoComprasDao _dao = getCarritoComprasDao();
			CarritoCompras _result[] = _dao.findWhereSubtotalEquals(subtotal);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereImpuestosEquals'
	 * 
	 * @param impuestos
	 */
	public static void findWhereImpuestosEquals(double impuestos)
	{
		try {
			CarritoComprasDao _dao = getCarritoComprasDao();
			CarritoCompras _result[] = _dao.findWhereImpuestosEquals(impuestos);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getCarritoComprasDao'
	 * 
	 * @return CarritoComprasDao
	 */
	public static CarritoComprasDao getCarritoComprasDao()
	{
		return CarritoComprasDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(CarritoCompras dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdCARRITO() );
		buf.append( ", " );
		buf.append( dto.getTotal() );
		buf.append( ", " );
		buf.append( dto.getSubtotal() );
		buf.append( ", " );
		buf.append( dto.getImpuestos() );
		System.out.println( buf.toString() );
	}

}
